apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rbac-escalate-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-rbac-escalate-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
